
os: linux
arch:
 - amd64
 - ppc64le
language: cpp

compiler:
  - gcc
  - clang
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev
  
script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_TESTING=yes
  - make
  - make test
